name: Setup Fastreleaser
description: Download and install fastreleaser v1.0.0, verify version

inputs:
  github-token:
    description: 'GitHub token with read access to localcompose/fastreleaser (default: GITHUB_TOKEN)'
    default: ${{ github.token }}
    required: false

runs:
  using: composite
  steps:
    - name: Download fastreleaser v1.0.0
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        gh release download v1.0.0 \
          --pattern fastreleaser \
          --repo localcompose/fastreleaser \
          --dir .
        chmod +x ./fastreleaser
        sudo mv  ./fastreleaser /usr/local/bin/

    - name: Check fastreleaser version
      shell: bash
      run: fastreleaser -v || fastreleaser

    - name: Set Fastreleaser user.email and user.name
      shell: bash
      run: >-
        git config --global user.email "fastreleaser@locom.ninja" ;
        git config --global user.name "FastReleaser" ;
